type: Dataplane
mesh: default
name: service1
networking:
  inbound:
    - port: 8001
      servicePort: 8000
      serviceAddress: 127.0.0.1
      tags:
        kuma.io/service: service1-8000
        kuma.io/protocol: http
probes:
  port: 65000
  endpoints:
    - inboundPort: 8000
      inboundPath: /health
      path: /8000/health
